#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Extract numeric Warthog phys tags from the owner's Xbox build-2276 cache."""
import argparse,importlib.util,struct,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
s=importlib.util.spec_from_file_location('cache',ROOT/'scripts/extract-halo.py');h=importlib.util.module_from_spec(s);s.loader.exec_module(h)
def extract(c):
 tag=next((t for t in c.index if t['class']=='phys' and t['path']=='vehicles\\warthog\\warthog'),None)
 if tag is None:raise h.CacheError('Warthog physics tag not found')
 o=tag['offset'];c.check(o,128)
 values=struct.unpack_from('<23f',c.data,o);n,ptr=struct.unpack_from('<II',c.data,o+116)
 if not 1<=n<=32 or values[2]<=0 or values[9]<=0 or min(values[20:23])<=0:raise h.CacheError('Invalid Warthog physics')
 start=c.pointer(ptr,n*128);points=[]
 for i in range(n):
  q=start+i*128;powered,node=struct.unpack_from('<hh',c.data,q+32);mass=struct.unpack_from('<f',c.data,q+44)[0];pos=struct.unpack_from('<3f',c.data,q+56);kind=struct.unpack_from('<h',c.data,q+92)[0];parallel,perpendicular,radius=struct.unpack_from('<3f',c.data,q+96)
  if not all(math.isfinite(x) for x in (*pos,mass,parallel,perpendicular,radius)) or min(parallel,perpendicular)<0:raise h.CacheError('Invalid mass point values')
  if powered not in (-1,0,1) or kind not in (0,1) or not 0<mass<=values[2] or radius<=0:raise h.CacheError('Unsupported mass point')
  points.append((tuple(x*80 for x in pos),mass/values[2],radius*80,parallel,perpendicular,powered,kind,node))
 if not all(math.isfinite(x) for x in values):raise h.CacheError('Nonfinite physics')
 return values,points

def header(c):
 v,points=extract(c)
 def f(x):
  value=format(x,'.9g')
  return value+('.0' if '.' not in value and 'e' not in value else '')+'f'
 text=['/* SPDX-License-Identifier: GPL-3.0-only',' * Numeric Xbox 2276 Warthog physics; generated by extract-halo-vehicle-physics.py.',' * Source cache SHA256: '+c.header['sha256'],' */','#define QCE_HOG_POINT_COUNT '+str(len(points)), '#define QCE_HOG_GROUND_DEPTH '+f(v[9]*80),'#define QCE_HOG_GROUND_DAMP '+f(v[10]*30),'#define QCE_HOG_GROUND_FRICTION '+f(v[8]*30),'#define QCE_HOG_AIR_FRICTION '+f(v[18]*30),'#define QCE_HOG_GRAVITY_SCALE '+f(v[7]),'#define QCE_HOG_NORMAL_K0 '+f(v[12]),'#define QCE_HOG_NORMAL_K1 '+f(v[11]),'static const vec3_t qceHogCOM={'+','.join(f(x*80) for x in v[3:6])+'};','static const vec3_t qceHogInertiaPerMass={'+','.join(f(x*80*80/v[2]) for x in v[20:23])+'};','static const qce_hogpoint_t qceHogPoints[QCE_HOG_POINT_COUNT]={']
 for pos,m,r,pa,pe,powered,kind,node in points:text.append(' {{'+','.join(f(x) for x in pos)+'},'+','.join(f(x) for x in (m,r,pa,pe))+','+','.join(str(x) for x in (powered,kind,node))+'},')
 return '\n'.join(text+['};',''])
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('map');p.add_argument('--header',required=True);a=p.parse_args();Path(a.header).write_text(header(h.XboxMap(a.map)))
