#!/usr/bin/env python3
"""Validate the gameplay profile and emit shared C89/QVM-compatible definitions."""
import argparse,hashlib,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ORDER=['WP_NONE','WP_GAUNTLET','WP_MACHINEGUN','WP_SHOTGUN','WP_GRENADE_LAUNCHER','WP_ROCKET_LAUNCHER','WP_LIGHTNING','WP_RAILGUN','WP_PLASMAGUN','WP_BFG','WP_GRAPPLING_HOOK','WP_NAILGUN','WP_PROX_LAUNCHER','WP_CHAINGUN']
KINDS=['none','melee','bullet','shotgun','grenade','rocket','lightning','rail','plasma']
FIELDS=['magazine','reload_ms','fire_ms','damage','spread','recoil_degrees','fire_kind','projectile_speed','splash_damage','splash_radius','fuse_ms','shield_multiplier','health_multiplier','headshot_mode','melee_damage','melee_reach','lunge_reach','lunge_speed','melee_impact_ms','melee_ms','pellets']
GFIELDS=['spawn_count','max_count','throw_speed','fuse_ms','sticky','splash_damage','splash_radius','shield_multiplier','health_multiplier']
INTS={'magazine','reload_ms','fire_ms','damage','splash_damage','fuse_ms','headshot_mode','melee_damage','melee_impact_ms','melee_ms','pellets','spawn_count','max_count'}
def validate(p):
 if p['schema_version']!=1 or p['status'] not in ('provisional','reference'):raise ValueError('Unsupported profile schema/status')
 if set(p['weapons'])!=set(ORDER):raise ValueError('Weapon membership must match the engine slots')
 if p['units']['distance']!='quake_units' or p['units']['time']!='milliseconds':raise ValueError('Convert values to engine units before generating')
 if p['status']=='reference' and (not p['provenance']['reference_build'] or not p['provenance']['source_maps'] or not p['provenance']['source_tag_hashes']):raise ValueError('Reference profiles require build, maps and tag hashes')
 for key,w in p['weapons'].items():
  if set(w)!=set(FIELDS+['name']):raise ValueError(f'{key}: unknown/missing fields')
  if w['fire_kind'] not in KINDS:raise ValueError(f'{key}: invalid firing behavior')
  numeric={k:w[k] for k in FIELDS if k!='fire_kind'}
  for k,v in numeric.items():
   if type(v) not in (int,float) or not math.isfinite(v) or v<0 or v>1000000:raise ValueError(f'{key}.{k}: invalid nonnegative value')
   if k in INTS and type(v)!=int:raise ValueError(f'{key}.{k}: integer required')
  if w['headshot_mode'] and w['fire_kind'] not in ('bullet','rail'):raise ValueError(f'{key}: headshot policy requires precision bullet/rail firing')
  if w['magazine']>200 or w['headshot_mode'] not in (0,1,2) or w['fire_ms']<1 or w['reload_ms']<1 or not 1<=w['pellets']<=64:raise ValueError(f'{key}: invalid capacity/timing/policy')
  if not 0<w['shield_multiplier']<=16 or not 0<=w['health_multiplier']<=16 or w['lunge_reach']<w['melee_reach'] or not 0<w['melee_impact_ms']<w['melee_ms']:raise ValueError(f'{key}: invalid damage/melee scaling')
 if len(p['grenades'])!=2:raise ValueError('Exactly frag/plasma grenade definitions are required')
 for i,g in enumerate(p['grenades']):
  if set(g)!=set(GFIELDS+['name']) or g['name']!=['frag','plasma'][i] or type(g['sticky'])!=bool:raise ValueError('Invalid grenade definition')
  for k in GFIELDS:
   if k=='sticky':continue
   v=g[k]
   if type(v) not in (int,float) or not math.isfinite(v) or v<0 or v>1000000 or (k in INTS and type(v)!=int):raise ValueError(f'Invalid grenade {k}')
  if not 0<=g['spawn_count']<=g['max_count']<=4 or g['fuse_ms']<1 or not 0<g['shield_multiplier']<=16 or not 0<=g['health_multiplier']<=16:raise ValueError('Invalid grenade capacity/timing/scaling')
 return p
def literal(k,v):
 if k=='fire_kind':return str(KINDS.index(v))
 if type(v) is bool:return str(int(v))
 if k in INTS:return str(v)
 return format(float(v),'.8f')+'f'
def render(p):
 digest=hashlib.sha256(json.dumps(p,sort_keys=True,separators=(',',':')).encode()).hexdigest()
 lines=['/* Generated by scripts/generate-profile.py; edit data/gameplay-profile.json. */',f'#define QCE_PROFILE_SHA "{digest}"','static const qce_weapondef_t qce_weapondefs[WP_NUM_WEAPONS] = {']
 for i,key in enumerate(ORDER):
  if i==11:lines.append('#ifdef MISSIONPACK')
  w=p['weapons'][key];lines.append(' { '+', '.join(literal(k,w[k]) for k in FIELDS)+' }, /* '+key+' */')
 lines+=['#endif','};','static const qce_grenadedef_t qce_grenadedefs[2] = {']
 for g in p['grenades']:lines.append(' { '+', '.join(literal(k,g[k]) for k in GFIELDS)+' },')
 lines+=['};','']
 return '\n'.join(lines)
def main():
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');parser.add_argument('--profile',type=Path,default=ROOT/'data/gameplay-profile.json');args=parser.parse_args()
 contents=render(validate(json.loads(args.profile.read_text())))
 dest=ROOT/'engine/code/game/bg_qce_profile.generated.h'
 if args.check:
  if not dest.exists() or dest.read_text()!=contents:raise SystemExit('Generated profile is stale; run scripts/generate-profile.py')
 elif not dest.exists() or dest.read_text()!=contents:dest.write_text(contents)
if __name__=='__main__':main()
