#!/usr/bin/env python3
"""Import grenade animation/particle scalars from the owner's Xbox cache.
Generated art is excluded; this audit records numeric data and source hashes.
"""
import argparse, importlib.util, json, math, struct
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location('halo',ROOT/'scripts/extract-halo.py')
halo=importlib.util.module_from_spec(spec);spec.loader.exec_module(halo)
def extract(path):
 c=halo.XboxMap(path)
 def refs(offset,stride):
  c.check(offset,12);count,pointer=struct.unpack_from('<II',c.data,offset)
  if count>128:raise halo.CacheError('Presentation reflexive limit')
  start=c.pointer(pointer,count*stride) if count else 0
  return [start+i*stride for i in range(count)]
 anim=next(a for a in c.tag('characters\\cyborg\\cyborg','antr')['values']['animations'] if a['name']=='stand rifle throw-grenade')
 out={'source_map':c.header,'grenade_release_frame':anim['key frame index'],'animation_fps':30,'blend_ticks':6,'idle_blend_ticks':1,'behavior_reference':{'repository':'https://github.com/cybersecurity/halo-ce-universal','commit':'73dc01d09a21875f14c77b4430f20518d1f5ad09','functions':['unit_throw_grenade_release','unit_animation_compute_interpolation_frame_count','animation_update_internal']},'particles':[]}
 for path in ('weapons\\frag grenade\\effects\\explosion med','weapons\\plasma grenade\\effects\\explosion'):
  tag=next(t for t in c.index if t['class']=='pctl' and t['path']==path)
  types=refs(tag['offset']+92,128)
  if len(types)!=1:raise halo.CacheError('Unexpected grenade particle type count')
  t=types[0];states=[]
  lifecycle=refs(t+104,192)
  if len(lifecycle)!=2:raise halo.CacheError('Unexpected emitter states')
  birth,death=lifecycle
  constants=refs(t+92,4)
  if len(constants)!=3:raise halo.CacheError('Unexpected explosion physics constants')
  explosion=[struct.unpack_from('<f',c.data,o)[0] for o in constants]
  color=[list(struct.unpack_from('<4f',c.data,o+64)) for o in lifecycle]

  for o in refs(t+116,376):
   physics_id=struct.unpack_from('<I',c.data,o+144)[0];physics=c.tags[physics_id]
   if physics['class']!='pphy':raise halo.CacheError('Expected point physics')
   po=physics['offset'];c.check(po,64)
   radius=struct.unpack_from('<f',c.data,t+44)[0]*struct.unpack_from('<f',c.data,birth+80)[0]*struct.unpack_from('<f',c.data,o+128)[0]
   flags=struct.unpack_from('<I',c.data,po)[0]
   states.append({'name':c.cstring(o,32),'point_physics':physics['path'],'mass':struct.unpack_from('<f',c.data,po+4)[0],'buoyancy':0 if flags&32 else struct.unpack_from('<f',c.data,po+12)[0],'friction':struct.unpack_from('<f',c.data,po+36)[0],'radius':radius,'duration':list(struct.unpack_from('<2f',c.data,o+32)), 'transition':list(struct.unpack_from('<2f',c.data,o+40)), 'scale':list(struct.unpack_from('<2f',c.data,o+72)), 'rotation':list(struct.unpack_from('<2f',c.data,o+88)), 'argb_min':list(struct.unpack_from('<4f',c.data,o+96)), 'argb_max':list(struct.unpack_from('<4f',c.data,o+112))})
  if len(states)!=3:raise halo.CacheError('Unexpected grenade state count')
  out['particles'].append({'tag':path,'count':struct.unpack_from('<h',c.data,t+36)[0],'states':states,'explosion':explosion,'emitter_duration':list(struct.unpack_from('<2f',c.data,birth+32)),'emitter_transition':list(struct.unpack_from('<2f',c.data,birth+40)),'type_color':color,'creation_rate':[struct.unpack_from('<f',c.data,o+88)[0] for o in lifecycle]})
 return out

def render(data):
 def f(x):
  if not math.isfinite(x):raise ValueError('Nonfinite source scalar')
  return format(x,'.9f')+'f'
 lines=['/* Generated by scripts/import-halo-presentation.py; numeric Xbox tag values only. */', '#ifndef BG_QCE_PRESENTATION_GENERATED_H','#define BG_QCE_PRESENTATION_GENERATED_H',f'#define QCE_GRENADE_RELEASE_MS {round(data["grenade_release_frame"]*1000/data["animation_fps"])}',f'#define QCE_POSE_BLEND_MS {round(data["blend_ticks"]*1000/data["animation_fps"])}',f'#define QCE_IDLE_POSE_BLEND_MS {round(data["idle_blend_ticks"]*1000/data["animation_fps"])}']
 lines+=['typedef struct { float duration[2],transition[2],scale[2],rotation[2],argbMin[4],argbMax[4]; float mass,buoyancy,friction,radius; } qce_particle_state_t;', 'typedef struct { int count; float explosion[3],emitterDuration[2],emitterTransition[2],typeColor[2][4],creationRate[2]; qce_particle_state_t states[3]; } qce_particle_type_t;', '#ifdef QCE_DEFINE_PARTICLE_DATA','static const qce_particle_type_t qce_grenade_particles[2] = {']
 for p in data['particles']:
  lines.append(' { '+str(p['count'])+', '+', '.join('{'+','.join(f(x) for x in p[k])+'}' for k in ('explosion','emitter_duration','emitter_transition'))+', {'+','.join('{'+','.join(f(x) for x in v)+'}' for v in p['type_color'])+'}, {'+','.join(f(x) for x in p['creation_rate'])+'}, {')
  for s in p['states']:lines.append('  { '+', '.join('{'+','.join(f(x) for x in s[k])+'}' for k in ('duration','transition','scale','rotation','argb_min','argb_max'))+', '+', '.join(f(s[k]) for k in ('mass','buoyancy','friction','radius'))+' },')
  lines.append(' } },')
 return '\n'.join(lines+['};','#endif','#endif',''])
def main():
 a=argparse.ArgumentParser();a.add_argument('map',type=Path,nargs='?');a.add_argument('--check',action='store_true');args=a.parse_args()
 audit=ROOT/'data/halo-presentation-timing.json';header=ROOT/'engine/code/game/bg_qce_presentation.generated.h'
 data=extract(args.map) if args.map else json.loads(audit.read_text());text=render(data)
 if args.check:
  if header.read_text()!=text:raise SystemExit('Presentation header is stale')
 else:
  audit.write_text(json.dumps(data,indent=2)+'\n');header.write_text(text)
if __name__=='__main__':main()
